version: '3.8'
services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    container_name: device_location
    restart: on-failure
    environment:
      MONGO_URI: mongodb://admin:password@mongo:27017
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo_data:
